CREATE TABLE TEST2(ID INT PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), ADDRESS VARCHAR(255));
INSERT INTO TEST2 VALUES(1, 'Arif', 'Wider', 'Treskowallee');
INSERT INTO TEST2 VALUES(2, 'Lucas', 'Larisch', 'Treskowallee');
